class AppStrings {
  AppStrings._();

  static const Map<String, Map<String, String>> _strings = {
    // ===== عام =====
    'app_name': {'ar': 'All Owners', 'en': 'All Owners'},
    'app_tagline': {'ar': 'فندقك، أينما كنت', 'en': 'Your stay, anywhere'},
    'continue': {'ar': 'استمرار', 'en': 'Continue'},
    'next': {'ar': 'التالي', 'en': 'Next'},
    'skip': {'ar': 'تخطي', 'en': 'Skip'},
    'back': {'ar': 'رجوع', 'en': 'Back'},
    'cancel': {'ar': 'إلغاء', 'en': 'Cancel'},
    'confirm': {'ar': 'تأكيد', 'en': 'Confirm'},
    'save': {'ar': 'حفظ', 'en': 'Save'},
    'search': {'ar': 'بحث', 'en': 'Search'},
    'see_all': {'ar': 'عرض الكل', 'en': 'See all'},
    'loading': {'ar': 'جاري التحميل...', 'en': 'Loading...'},
    'night': {'ar': 'ليلة', 'en': 'night'},
    'nights': {'ar': 'ليالٍ', 'en': 'nights'},
    'guests': {'ar': 'ضيوف', 'en': 'guests'},
    'sar': {'ar': 'ريال', 'en': 'SAR'},
    'one_time_fee': {'ar': 'رسم مرة واحدة', 'en': 'one-time fee'},
    'choose_from_gallery': {'ar': 'اختر من المعرض', 'en': 'Choose from gallery'},
    'take_photo': {'ar': 'التقاط صورة', 'en': 'Take a photo'},
    'remove_photo': {'ar': 'حذف الصورة', 'en': 'Remove photo'},
    'avatar_update_failed': {'ar': 'تعذّر تحديث الصورة، حاول مرة ثانية', 'en': 'Could not update photo, try again'},

    // ===== Onboarding =====
    'onboard_title_1': {'ar': 'مرحبًا بك في All Owners', 'en': 'Welcome to All Owners'},
    'onboard_desc_1': {
      'ar': 'المنصة الموثوقة لملاك الوحدات الفندقية والعقارات، وتجربة حجز ذكية للضيوف.',
      'en': 'The Trusted Platform for Hotel Unit & Property Owners, with a Smart Booking Experience for Guests.'
    },
    'onboard_title_2': {'ar': 'للملاك', 'en': 'For Property Owners'},
    'onboard_desc_2': {
      'ar': 'نوفر منصة متكاملة تمكّن الملاك من إدارة ممتلكاتهم ومتابعة الحجوزات، والإيرادات، والعقود، والصيانة والنظافة، والتواصل مع إدارات الفنادق وشركات التشغيل، بكل سهولة وأمان.',
      'en': 'An integrated platform that enables property owners to manage their properties, track bookings, revenues, contracts, maintenance and housekeeping, and communicate with hotel management and operating companies.'
    },
    'onboard_title_3': {'ar': 'للضيوف والوكلاء', 'en': 'For Guests & Agents'},
    'onboard_desc_3': {
      'ar': 'كما تتيح للضيوف والوكلاء البحث عن الوحدات المتاحة، وإجراء الحجوزات والدفع الإلكتروني، وإدارة الإقامة بكل سهولة وأمان.\n\nكل ما تحتاجه لإدارة ممتلكاتك أو حجز إقامتك... في منصة واحدة آمنة وذكية.',
      'en': 'Guests and booking agents can search for available units, make reservations, complete secure online payments, and manage their stays with ease.\n\nEverything you need to manage your property or book your stay — all in one secure and smart platform.'
    },
    'get_started': {'ar': 'ابدأ الآن', 'en': 'Get Started'},

    // ===== Auth =====
    'login': {'ar': 'تسجيل الدخول', 'en': 'Login'},
    'register': {'ar': 'إنشاء حساب', 'en': 'Register'},
    'welcome_back': {'ar': 'مرحباً بعودتك', 'en': 'Welcome Back'},
    'login_subtitle': {'ar': 'سجّل دخولك للمتابعة', 'en': 'Sign in to continue'},
    'phone_number': {'ar': 'رقم الهاتف', 'en': 'Phone Number'},
    'email': {'ar': 'البريد الإلكتروني', 'en': 'Email'},
    'password': {'ar': 'كلمة المرور', 'en': 'Password'},
    'full_name': {'ar': 'الاسم الكامل', 'en': 'Full Name'},
    'forgot_password': {'ar': 'نسيت كلمة المرور؟', 'en': 'Forgot Password?'},
    'no_account': {'ar': 'ليس لديك حساب؟', 'en': "Don't have an account?"},
    'have_account': {'ar': 'لديك حساب؟', 'en': 'Already have an account?'},
    'create_account': {'ar': 'إنشاء حساب جديد', 'en': 'Create New Account'},
    'or_continue_with': {'ar': 'أو الاستمرار باستخدام', 'en': 'Or continue with'},
    'continue_as_guest': {'ar': 'الاستمرار كزائر', 'en': 'Continue as Guest'},

    // ===== Home =====
    'home': {'ar': 'الرئيسية', 'en': 'Home'},
    'hello': {'ar': 'مرحباً', 'en': 'Hello'},
    'hello_guest': {'ar': 'مرحبًا بك', 'en': 'Welcome'},
    'where_to': {'ar': 'أين ترغب في الإقامة؟', 'en': 'Where would you like to stay?'},
    'search_destination': {'ar': 'ابحث عن مدينة أو وحدة أو عقار', 'en': 'Search city, unit or property'},
    'check_in': {'ar': 'تاريخ الوصول', 'en': 'Check-in'},
    'check_out': {'ar': 'تاريخ المغادرة', 'en': 'Check-out'},
    'categories': {'ar': 'التصنيفات', 'en': 'Categories'},
    'hotels': {'ar': 'الوحدات الفندقية', 'en': 'Hotel Units'},
    'apartments': {'ar': 'شقق مفروشة', 'en': 'Furnished Apartments'},
    'resorts': {'ar': 'منتجعات', 'en': 'Resorts'},
    'chalets': {'ar': 'شاليهات', 'en': 'Chalets'},
    'properties': {'ar': 'عقارات', 'en': 'Properties'},
    'owner_units': {'ar': 'وحدات الملاك', 'en': "Owners' Units"},
    'hotels_with_owner_units': {'ar': 'فنادق بوحدات ملاك', 'en': 'Hotels with Owner Units'},
    'units_available_count': {'ar': 'وحدة متاحة للحجز', 'en': 'units available for booking'},
    'featured_deals': {'ar': 'عروض مميزة', 'en': 'Featured Deals'},
    'newest_suites': {'ar': 'أحدث الوحدات', 'en': 'Newest Units'},
    'my_commission': {'ar': 'عمولتي', 'en': 'My Commission'},
    'commission_setting': {'ar': 'إعداد العمولة الحالي', 'en': 'Current commission setting'},
    'set_by_admin_only': {'ar': 'يحدّدها الأدمن فقط', 'en': 'set by admin only'},
    'total_bookings': {'ar': 'إجمالي الحجوزات', 'en': 'Total Bookings'},
    'total_commission': {'ar': 'إجمالي العمولة', 'en': 'Total Commission'},
    'paid': {'ar': 'مدفوعة', 'en': 'Paid'},
    'unpaid': {'ar': 'غير مدفوعة', 'en': 'Unpaid'},
    'commission_history': {'ar': 'سجل العمولات', 'en': 'Commission History'},
    'any': {'ar': 'أي عدد', 'en': 'Any'},
    'change_password_optional': {'ar': 'تغيير كلمة المرور (اختياري)', 'en': 'Change password (optional)'},
    'current_password': {'ar': 'كلمة المرور الحالية', 'en': 'Current password'},
    'new_password': {'ar': 'كلمة المرور الجديدة', 'en': 'New password'},
    'phone': {'ar': 'رقم الجوال', 'en': 'Phone'},
    'availability_periods': {'ar': 'فترات الإتاحة للحجز', 'en': 'Availability Periods'},
    'add_period': {'ar': 'إضافة فترة', 'en': 'Add period'},
    'no_periods_yet': {'ar': 'ما في فترات إتاحة محددة بعد', 'en': 'No availability periods set yet'},
    'sort_newest': {'ar': 'الأحدث', 'en': 'Newest'},
    'sort_price_asc': {'ar': 'الأقل سعراً', 'en': 'Lowest Price'},
    'sort_capacity': {'ar': 'الأكبر سعة', 'en': 'Largest'},
    'popular_destinations': {'ar': 'وجهات شائعة', 'en': 'Popular Destinations'},
    'recommended_for_you': {'ar': 'موصى به لك', 'en': 'Recommended for You'},
    'per_night': {'ar': '/ليلة', 'en': '/night'},

    // ===== Search & Filters =====
    'search_results': {'ar': 'نتائج البحث', 'en': 'Search Results'},
    'results_found': {'ar': 'نتيجة', 'en': 'results found'},
    'filters': {'ar': 'الفلاتر', 'en': 'Filters'},
    'sort_by': {'ar': 'ترتيب حسب', 'en': 'Sort by'},
    'price_range': {'ar': 'نطاق السعر', 'en': 'Price Range'},
    'star_rating': {'ar': 'تصنيف النجوم', 'en': 'Star Rating'},
    'property_type': {'ar': 'نوع العقار', 'en': 'Property Type'},
    'amenities': {'ar': 'المرافق', 'en': 'Amenities'},
    'apply_filters': {'ar': 'تطبيق الفلاتر', 'en': 'Apply Filters'},
    'reset': {'ar': 'إعادة تعيين', 'en': 'Reset'},
    'no_results': {'ar': 'لا توجد نتائج مطابقة', 'en': 'No matching results'},
    'price_low_high': {'ar': 'السعر: من الأقل للأعلى', 'en': 'Price: Low to High'},
    'price_high_low': {'ar': 'السعر: من الأعلى للأقل', 'en': 'Price: High to Low'},
    'top_rated': {'ar': 'الأعلى تقييماً', 'en': 'Top Rated'},
    'distance': {'ar': 'الأقرب', 'en': 'Nearest'},

    // ===== Hotel Details =====
    'overview': {'ar': 'نظرة عامة', 'en': 'Overview'},
    'rooms': {'ar': 'الغرف', 'en': 'Rooms'},
    'reviews': {'ar': 'تقييم', 'en': 'reviews'},
    'location': {'ar': 'الموقع', 'en': 'Location'},
    'show_more': {'ar': 'عرض المزيد', 'en': 'Show more'},
    'show_less': {'ar': 'عرض أقل', 'en': 'Show less'},
    'about_property': {'ar': 'عن العقار', 'en': 'About this property'},
    'available_rooms': {'ar': 'الغرف المتاحة', 'en': 'Available Rooms'},
    'select_room': {'ar': 'اختر الغرفة', 'en': 'Select Room'},
    'free_cancellation': {'ar': 'إلغاء مجاني', 'en': 'Free cancellation'},
    'breakfast_included': {'ar': 'الإفطار مشمول', 'en': 'Breakfast included'},
    'pay_at_property': {'ar': 'الدفع بالفندق متاح', 'en': 'Pay at the property'},
    'view_on_map': {'ar': 'عرض على الخريطة', 'en': 'View on map'},
    'guest_reviews': {'ar': 'تقييمات الضيوف', 'en': 'Guest Reviews'},
    'see_all_reviews': {'ar': 'عرض كل التقييمات', 'en': 'See all reviews'},
    'select_dates': {'ar': 'اختر تواريخك', 'en': 'Select Your Dates'},
    'book_now': {'ar': 'احجز الآن', 'en': 'Book Now'},

    // ===== Booking =====
    'booking_summary': {'ar': 'ملخص الحجز', 'en': 'Booking Summary'},
    'your_stay': {'ar': 'مدة إقامتك', 'en': 'Your Stay'},
    'guest_details': {'ar': 'بيانات الضيف', 'en': 'Guest Details'},
    'payment_method': {'ar': 'طريقة الدفع', 'en': 'Payment Method'},
    'pay_online': {'ar': 'الدفع الإلكتروني الآن', 'en': 'Pay Online Now'},
    'pay_at_hotel': {'ar': 'الدفع عند الوصول بالفندق', 'en': 'Pay at the Hotel'},
    'pay_owner_transfer': {'ar': 'تحويل مباشر لحساب المالك', 'en': 'Direct Transfer to Owner'},
    'card_number': {'ar': 'رقم البطاقة', 'en': 'Card Number'},
    'expiry_date': {'ar': 'تاريخ الانتهاء', 'en': 'Expiry Date'},
    'cvv': {'ar': 'رمز الأمان CVV', 'en': 'CVV'},
    'cardholder_name': {'ar': 'اسم حامل البطاقة', 'en': 'Cardholder Name'},
    'price_details': {'ar': 'تفاصيل السعر', 'en': 'Price Details'},
    'room_price': {'ar': 'سعر الغرفة', 'en': 'Room Price'},
    'taxes_fees': {'ar': 'الضرائب والرسوم', 'en': 'Taxes & Fees'},
    'total_price': {'ar': 'الإجمالي', 'en': 'Total Price'},
    'confirm_booking': {'ar': 'تأكيد الحجز', 'en': 'Confirm Booking'},
    'booking_success': {'ar': 'تم تأكيد حجزك بنجاح', 'en': 'Your booking is confirmed'},
    'booking_success_desc': {
      'ar': 'تفاصيل حجزك جاهزة، نتمنى لك رحلة سعيدة',
      'en': 'Your booking details are ready. Have a great trip!'
    },
    'booking_reference': {'ar': 'رقم الحجز', 'en': 'Booking Reference'},
    'view_booking': {'ar': 'عرض الحجز', 'en': 'View Booking'},

    // ===== My Bookings =====
    'my_bookings': {'ar': 'حجوزاتي', 'en': 'My Bookings'},
    'upcoming': {'ar': 'القادمة', 'en': 'Upcoming'},
    'past': {'ar': 'السابقة', 'en': 'Past'},
    'cancelled': {'ar': 'ملغية', 'en': 'Cancelled'},
    'no_bookings_yet': {'ar': 'لا توجد حجوزات حتى الآن', 'en': 'No bookings yet'},
    'cancel_booking': {'ar': 'إلغاء الحجز', 'en': 'Cancel Booking'},
    'confirm_cancel_booking': {'ar': 'هل أنت متأكد من إلغاء هذا الحجز؟', 'en': 'Are you sure you want to cancel this booking?'},
    'booking_details': {'ar': 'تفاصيل الحجز', 'en': 'Booking Details'},
    'confirm_booking_dialog_title': {'ar': 'تأكيد الحجز', 'en': 'Confirm Booking'},
    'confirm_booking_dialog_body': {
      'ar': 'سيتم تأكيد الحجز وإبلاغ الفندق والعميل تلقائياً بالإيميل.',
      'en': 'The booking will be confirmed and the hotel and guest will be notified automatically by email.'
    },
    'booking_confirmed_notified': {'ar': 'تم تأكيد الحجز وإبلاغ الأطراف', 'en': 'Booking confirmed — everyone notified'},
    'edit_booking': {'ar': 'تعديل الحجز', 'en': 'Edit Booking'},
    'guest_name': {'ar': 'اسم الضيف', 'en': 'Guest Name'},
    'guest_phone': {'ar': 'جوال الضيف', 'en': 'Guest Phone'},
    'save_changes': {'ar': 'حفظ التعديلات', 'en': 'Save Changes'},
    'booking_updated': {'ar': 'تم تعديل الحجز', 'en': 'Booking updated'},
    'customer_name': {'ar': 'اسم العميل', 'en': 'Customer Name'},
    'customer_phone': {'ar': 'جوال العميل', 'en': 'Customer Phone'},

    // ===== Favorites =====
    'favorites': {'ar': 'المفضلة', 'en': 'Favorites'},
    'no_favorites_yet': {'ar': 'لم تضف أي فندق للمفضلة بعد', 'en': 'No favorites yet'},

    // ===== Profile =====
    'profile': {'ar': 'حسابي', 'en': 'Profile'},
    'edit_profile': {'ar': 'تعديل الملف الشخصي', 'en': 'Edit Profile'},
    'payment_methods': {'ar': 'وسائل الدفع', 'en': 'Payment Methods'},
    'notifications': {'ar': 'الإشعارات', 'en': 'Notifications'},
    'language': {'ar': 'اللغة', 'en': 'Language'},
    'settings': {'ar': 'الإعدادات', 'en': 'Settings'},
    'help_support': {'ar': 'المساعدة والدعم', 'en': 'Help & Support'},
    'help_support_intro': {'ar': 'تواصل معنا بأي وقت عبر إحدى الطرق التالية:', 'en': 'Reach us anytime through one of the following:'},
    'contact_whatsapp': {'ar': 'واتساب', 'en': 'WhatsApp'},
    'contact_call': {'ar': 'اتصال', 'en': 'Call'},
    'contact_email': {'ar': 'البريد الإلكتروني', 'en': 'Email'},
    'about_us': {'ar': 'عن التطبيق', 'en': 'About Us'},
    'logout': {'ar': 'تسجيل الخروج', 'en': 'Logout'},

    // ===== Navigation =====
    'nav_home': {'ar': 'الرئيسية', 'en': 'Home'},
    'nav_search': {'ar': 'بحث', 'en': 'Search'},
    'nav_bookings': {'ar': 'حجوزاتي', 'en': 'Bookings'},
    'nav_favorites': {'ar': 'المفضلة', 'en': 'Favorites'},
    'nav_profile': {'ar': 'حسابي', 'en': 'Profile'},

    // ===== Hotel Services =====
    'available_services': {'ar': 'الخدمات المتاحة', 'en': 'Available Services'},
    'hotel_services': {'ar': 'خدمات الفندق', 'en': 'Hotel Services'},
    'maintenance': {'ar': 'الصيانة', 'en': 'Maintenance'},
    'maintenance_desc': {
      'ar': 'اطلب فني للإصلاحات داخل الغرفة',
      'en': 'Request a technician for in-room repairs'
    },
    'housekeeping': {'ar': 'النظافة', 'en': 'Cleaning'},
    'housekeeping_desc': {
      'ar': 'اطلب تنظيف الغرفة أو تغيير المناشف',
      'en': 'Request room cleaning or fresh towels'
    },
    'cancellation_request': {'ar': 'طلب إلغاء', 'en': 'Cancellation Request'},
    'cancellation_request_desc': {
      'ar': 'تقديم طلب إلغاء حجز أو خدمة',
      'en': 'Submit a booking or service cancellation request'
    },
    'room_number': {'ar': 'رقم الغرفة', 'en': 'Room Number'},
    'request_details': {'ar': 'تفاصيل الطلب', 'en': 'Request Details'},
    'describe_request': {'ar': 'اكتب تفاصيل طلبك هنا...', 'en': 'Describe your request here...'},
    'submit_request': {'ar': 'إرسال الطلب', 'en': 'Submit Request'},
    'request_submitted_title': {'ar': 'تم استلام طلبك', 'en': 'Request Received'},
    'request_submitted_desc': {
      'ar': 'سيقوم فريق الفندق بمتابعة طلبك في أقرب وقت ممكن',
      'en': 'The hotel team will follow up on your request as soon as possible'
    },
    'room_number_required': {'ar': 'الرجاء إدخال رقم الغرفة', 'en': 'Please enter your room number'},
    'ok': {'ar': 'حسناً', 'en': 'OK'},
    'order_meal': {'ar': 'طلب وجبة', 'en': 'Order a Meal'},
    'order_meal_desc': {
      'ar': 'اطلب وجبتك المفضلة وسيقوم فريق الفندق بتحضيرها',
      'en': 'Order your favorite meal and the hotel team will prepare it'
    },
    'meal_type': {'ar': 'نوع الوجبة', 'en': 'Meal Type'},
    'meal_option_none': {'ar': 'بدون وجبات', 'en': 'No meals'},
    'meal_multi_select_hint': {'ar': 'تقدر تختار أكثر من وجبة (فطور + غداء مثلاً)', 'en': 'You can select more than one meal (e.g. breakfast + lunch)'},
    'meal_option_breakfast': {'ar': 'فطور', 'en': 'Breakfast'},
    'meal_option_lunch': {'ar': 'غداء', 'en': 'Lunch'},
    'meal_option_dinner': {'ar': 'عشاء', 'en': 'Dinner'},
    'meal_option_all': {'ar': 'جميع الوجبات', 'en': 'All meals'},
    'add_extra_bed': {'ar': 'إضافة سرير إضافي', 'en': 'Add extra bed'},
    'free': {'ar': 'مجاني', 'en': 'Free'},
    'breakfast': {'ar': 'فطور', 'en': 'Breakfast'},
    'lunch': {'ar': 'غداء', 'en': 'Lunch'},
    'dinner': {'ar': 'عشاء', 'en': 'Dinner'},
    'meal_type_required': {'ar': 'الرجاء اختيار نوع الوجبة', 'en': 'Please select a meal type'},
    'notes': {'ar': 'ملاحظات', 'en': 'Notes'},
    'notes_hint': {
      'ar': 'اكتب ملاحظاتك هنا... (مثال: بدون سكر، حساسية من المكسرات)',
      'en': 'Write your notes here... (e.g. no sugar, nut allergy)'
    },

    // ===== Roles & Owner Dashboard =====
    'account_type': {'ar': 'نوع الحساب', 'en': 'Account Type'},
    'role_owner': {'ar': 'مالك', 'en': 'Owner'},
    'role_guest': {'ar': 'ضيف', 'en': 'Guest'},
    'coming_soon_desc': {
      'ar': 'هذه الميزة قيد التطوير وستكون متوفرة قريباً',
      'en': 'This feature is under development and will be available soon'
    },
    'nav_units': {'ar': 'وحداتي', 'en': 'My Units'},
    'nav_revenue': {'ar': 'الإيرادات', 'en': 'Revenue'},
    'quick_links': {'ar': 'روابط سريعة', 'en': 'Quick Links'},
    'owner_bookings': {'ar': 'الحجوزات', 'en': 'Bookings'},
    'hotel_requests': {'ar': 'الطلبات', 'en': 'Requests'},
    'service_prices': {'ar': 'الأسعار', 'en': 'Prices'},
    'financial_reports': {'ar': 'التقارير المالية', 'en': 'Financial Reports'},
    'contracts_docs': {'ar': 'العقود والمستندات', 'en': 'Contracts & Documents'},
    'maintenance_requests': {'ar': 'طلبات الصيانة', 'en': 'Maintenance Requests'},
    'voting_decisions': {'ar': 'التصويت والقرارات', 'en': 'Voting & Decisions'},
    'owners_community': {'ar': 'مجتمع الملاك', 'en': 'Owners Community'},
    'units_marketplace': {'ar': 'سوق الوحدات', 'en': 'Units Marketplace'},
    'units_marketplace_subtitle': {
      'ar': 'لعرض وحدة موجودة أصلاً للبيع أو الإيجار بين الملاك — مش لإضافة وحدة جديدة',
      'en': 'List an existing unit for sale/rent among owners — not for adding a new unit'
    },
    'messages': {'ar': 'الرسائل', 'en': 'Messages'},
    'staff': {'ar': 'الموظفون', 'en': 'Staff'},
    'staff_desc': {
      'ar': 'أضف مدير وحدة يدخل التطبيق باسمه، يستقبل بلاغات النظافة والصيانة، ويقدر يبدّل حالة الوحدة فقط',
      'en': 'Add a unit manager who logs in with their own account, receives housekeeping/maintenance reports, and can only toggle unit status'
    },
    'add_unit_manager': {'ar': 'إضافة مدير وحدة', 'en': 'Add Unit Manager'},
    'role_unit_manager': {'ar': 'مدير الوحدة', 'en': 'Unit Manager'},
    'role_hotel_manager': {'ar': 'إدارة الفندق', 'en': 'Hotel Management'},
    'role_booking_agent': {'ar': 'وكيل الحجوزات', 'en': 'Booking Agent'},
    'staff_permissions_note': {
      'ar': 'صلاحياته تلقائياً: مشاهدة الوحدات وتبديل حالتها، واستقبال بلاغات الصيانة والتنظيف. بدون حذف، وبدون أي وصول للمحفظة أو الإيرادات أو التقارير.',
      'en': 'Automatic permissions: view units and toggle their status, and receive maintenance/housekeeping reports. No delete, and no access to wallet, revenue, or reports.'
    },
    'password_hint_min6': {'ar': '6 أحرف على الأقل', 'en': 'At least 6 characters'},
    'no_staff_yet': {'ar': 'ما في موظفين مضافين بعد', 'en': 'No staff added yet'},
    'suspended': {'ar': 'موقوف', 'en': 'Suspended'},
    'suspend': {'ar': 'إيقاف', 'en': 'Suspend'},
    'activate': {'ar': 'تفعيل', 'en': 'Activate'},
    'reset_password': {'ar': 'كلمة المرور', 'en': 'Password'},
    'occupied': {'ar': 'مؤجرة', 'en': 'Occupied'},
    'vacant': {'ar': 'متاحة', 'en': 'Vacant'},
    'monthly_revenue': {'ar': 'الإيراد الشهري', 'en': 'Monthly Revenue'},
    'total_revenue_month': {'ar': 'إجمالي إيرادات هذا الشهر', 'en': 'Total Revenue This Month'},
    'revenue_history': {'ar': 'سجل الإيرادات', 'en': 'Revenue History'},
    'retry': {'ar': 'إعادة المحاولة', 'en': 'Retry'},
    'hotel_dashboard': {'ar': 'لوحة الفندق', 'en': 'Hotel Dashboard'},
    'arrivals_today': {'ar': 'وصول اليوم', 'en': 'Arrivals Today'},
    'departures_today': {'ar': 'مغادرة اليوم', 'en': 'Departures Today'},
    'in_house_now': {'ar': 'مقيمون حالياً', 'en': 'In House Now'},
    'open_requests': {'ar': 'طلبات مفتوحة', 'en': 'Open Requests'},
    'no_data': {'ar': 'لا توجد بيانات بعد', 'en': 'No data yet'},
    'error_loading': {'ar': 'حدث خطأ أثناء تحميل البيانات', 'en': 'Something went wrong loading the data'},
    'new_request': {'ar': 'طلب جديد', 'en': 'New Request'},
    'request_title': {'ar': 'عنوان الطلب', 'en': 'Request Title'},
    'description': {'ar': 'الوصف', 'en': 'Description'},
    'submit': {'ar': 'إرسال', 'en': 'Submit'},
    'send': {'ar': 'إرسال', 'en': 'Send'},
    'select_hotel': {'ar': 'اختر الفندق', 'en': 'Select Hotel'},
    'mark_all_read': {'ar': 'تعليم الكل كمقروء', 'en': 'Mark all as read'},
    'no_notifications': {'ar': 'لا توجد إشعارات', 'en': 'No notifications'},
    'no_bookings': {'ar': 'لا توجد حجوزات بعد', 'en': 'No bookings yet'},
    'my_clients': {'ar': 'عملائي', 'en': 'My Clients'},
    'add_client': {'ar': 'إضافة عميل', 'en': 'Add Client'},
    'edit_client': {'ar': 'تعديل العميل', 'en': 'Edit Client'},
    'client_email_optional': {'ar': 'البريد الإلكتروني (اختياري)', 'en': 'Email (optional)'},
    'confirm_delete_client': {'ar': 'هل أنت متأكد من حذف هذا العميل؟', 'en': 'Delete this client?'},
    'no_clients_yet': {'ar': 'ما أضفت أي عميل بعد — اضغط زر الإضافة أو احجز لعميل جديد وبينضاف تلقائيًا', 'en': 'No clients yet — tap add, or book for a new client and they will be added automatically'},
    'bookings_word': {'ar': 'حجز', 'en': 'bookings'},
    'book_for_client': {'ar': 'احجز لهذا العميل', 'en': 'Book for this client'},
    'delete': {'ar': 'حذف', 'en': 'Delete'},
    'client_details': {'ar': 'تفاصيل العميل', 'en': 'Client Details'},
    'client_bookings': {'ar': 'حجوزات العميل', 'en': 'Client Bookings'},
    'total': {'ar': 'الإجمالي', 'en': 'Total'},
    'commission_paid': {'ar': 'مدفوعة', 'en': 'paid'},
    'commission_unpaid': {'ar': 'غير مدفوعة', 'en': 'unpaid'},
    'commission_remaining': {'ar': 'المتبقي لك', 'en': 'Remaining'},
    'booking_status_label': {'ar': 'حالة الحجز', 'en': 'Booking status'},
    'booking_details_title': {'ar': 'تفاصيل الحجز', 'en': 'Booking details'},
    'view_booking_details': {'ar': 'عرض تفاصيل الحجز', 'en': 'View booking details'},
    'stay_dates': {'ar': 'فترة الإقامة', 'en': 'Stay dates'},
    'unit_label': {'ar': 'الوحدة', 'en': 'Unit'},
    'customer_label': {'ar': 'بيانات العميل', 'en': 'Customer'},
    'booking_created_at': {'ar': 'تاريخ ووقت الحجز', 'en': 'Booked on'},
    'payment_method_label': {'ar': 'طريقة الدفع', 'en': 'Payment method'},
    'pay_method_online': {'ar': 'دفع إلكتروني', 'en': 'Online payment'},
    'pay_method_at_hotel': {'ar': 'الدفع عند الوصول', 'en': 'Pay at hotel'},
    'pay_method_owner_transfer': {'ar': 'تحويل مباشر للمالك', 'en': 'Direct transfer to owner'},
    'saved_client': {'ar': 'عميل محفوظ', 'en': 'Saved client'},
    'new_client': {'ar': 'عميل جديد', 'en': 'New client'},
    'book_new_stay': {'ar': 'حجز جديد لعميل', 'en': 'New Booking for Client'},
    'select_booking': {'ar': 'اختر الحجز', 'en': 'Select Booking'},
    'no_confirmed_bookings': {'ar': 'ما فيه حجوزات مؤكدة حاليًا — الخدمة تتوفر بعد تأكيد الحجز', 'en': 'No confirmed bookings yet — services become available once a booking is confirmed'},
    'active_now': {'ar': 'الحالية', 'en': 'Active Now'},
    'history': {'ar': 'السجل', 'en': 'History'},
    'confirm_check_in': {'ar': 'تأكيد دخول الضيف', 'en': 'Confirm Guest Check-in'},
    'confirm_check_out': {'ar': 'تأكيد خروج الضيف', 'en': 'Confirm Guest Check-out'},
    'confirm_request': {'ar': 'تأكيد الطلب', 'en': 'Confirm Request'},
    'mark_done': {'ar': 'تم التنفيذ', 'en': 'Mark Done'},
    'reject_request': {'ar': 'رفض الطلب', 'en': 'Reject Request'},
    'price_optional': {'ar': 'السعر (اختياري)', 'en': 'Price (optional)'},
    'note_optional': {'ar': 'ملاحظة (اختياري)', 'en': 'Note (optional)'},
    'reject_reason': {'ar': 'سبب الرفض', 'en': 'Rejection reason'},
    'no_open_requests': {'ar': 'لا توجد طلبات حالياً', 'en': 'No requests right now'},
    'req_type_cleaning': {'ar': 'النظافة', 'en': 'Cleaning'},
    'req_type_maintenance': {'ar': 'الصيانة', 'en': 'Maintenance'},
    'req_type_meal': {'ar': 'الوجبات', 'en': 'Meals'},
    'req_type_extra_bed': {'ar': 'السرير الإضافي', 'en': 'Extra Bed'},
    'edit_price': {'ar': 'تعديل السعر', 'en': 'Edit Price'},
    'add_price': {'ar': 'إضافة سعر', 'en': 'Add Price'},
    'service_type': {'ar': 'نوع الخدمة', 'en': 'Service Type'},
    'unit_optional': {'ar': 'الجناح (اختياري)', 'en': 'Unit (optional)'},
    'all_units': {'ar': 'كل الأجنحة', 'en': 'All Units'},
    'no_prices_yet': {'ar': 'لم تضِف أسعار خدمات بعد', 'en': 'No service prices added yet'},
    'no_units': {'ar': 'لا توجد وحدات بعد', 'en': 'No units yet'},
    'available_units': {'ar': 'الأجنحة المتاحة', 'en': 'Available Units'},
    'guest_id_number': {'ar': 'رقم الهوية / الجواز', 'en': 'ID / Passport number'},
    'unit_type_ar': {'ar': 'نوع الوحدة (عربي)', 'en': 'Unit type (Arabic)'},
    'unit_type_en': {'ar': 'نوع الوحدة (إنجليزي)', 'en': 'Unit type (English)'},
    'bed_count': {'ar': 'عدد الأسرّة', 'en': 'Beds'},
    'guest_id_number_required': {'ar': 'الرجاء تعبئة رقم الهوية/الجواز', 'en': 'Please fill in the ID/passport number'},
    'customer_name_phone_required': {'ar': 'الرجاء إدخال اسم العميل ورقم جواله', 'en': 'Please enter the customer name and phone'},
    'no_maintenance': {'ar': 'لا توجد طلبات صيانة', 'en': 'No maintenance requests'},
    'meal_requests': {'ar': 'طلبات الوجبات', 'en': 'Meal Requests'},
    'no_meal_requests': {'ar': 'لا توجد طلبات وجبات حالياً', 'en': 'No meal requests yet'},
    'meal_breakfast': {'ar': 'فطور', 'en': 'Breakfast'},
    'meal_lunch': {'ar': 'غداء', 'en': 'Lunch'},
    'meal_dinner': {'ar': 'عشاء', 'en': 'Dinner'},
    'meal_status_pending': {'ar': 'قيد الانتظار', 'en': 'Pending'},
    'meal_status_preparing': {'ar': 'يتم التحضير', 'en': 'Preparing'},
    'meal_status_delivered': {'ar': 'تم التسليم', 'en': 'Delivered'},
    'meal_status_cancelled': {'ar': 'ملغي', 'en': 'Cancelled'},
    'room': {'ar': 'غرفة', 'en': 'Room'},
    'mark_preparing': {'ar': 'بدء التحضير', 'en': 'Start Preparing'},
    'mark_delivered': {'ar': 'تم التسليم', 'en': 'Mark Delivered'},
    'guest': {'ar': 'الضيف', 'en': 'Guest'},
    'total_amount': {'ar': 'الإجمالي', 'en': 'Total'},
    'request_sent': {'ar': 'تم إرسال الطلب بنجاح', 'en': 'Request sent successfully'},
    'by_unit': {'ar': 'حسب الوحدة', 'en': 'By Unit'},
    'pending_bookings': {'ar': 'حجوزات قيد الانتظار', 'en': 'Pending Bookings'},
    'status_open': {'ar': 'مفتوح', 'en': 'Open'},
    'status_in_progress': {'ar': 'قيد التنفيذ', 'en': 'In Progress'},
    'status_closed': {'ar': 'مغلق', 'en': 'Closed'},
    'status_pending': {'ar': 'قيد الانتظار', 'en': 'Pending'},
    'status_confirmed': {'ar': 'مؤكد', 'en': 'Confirmed'},
    'status_completed': {'ar': 'مكتمل', 'en': 'Completed'},
    'status_cancelled': {'ar': 'ملغى', 'en': 'Cancelled'},
    'status_checked_in': {'ar': 'تم تسجيل الدخول', 'en': 'Checked In'},
    'status_done': {'ar': 'تم التنفيذ', 'en': 'Done'},
    'status_rejected': {'ar': 'مرفوض', 'en': 'Rejected'},
    'new_cleaning_request': {'ar': 'طلب نظافة جديد', 'en': 'New Cleaning Request'},
    'no_units_yet': {'ar': 'ما عندك وحدات بعد', 'en': 'You have no units yet'},
    'no_cleaning_requests': {'ar': 'لا توجد طلبات نظافة', 'en': 'No cleaning requests'},
    'hotel_note': {'ar': 'ملاحظة الفندق', 'en': 'Hotel note'},
    'cancel_request': {'ar': 'إلغاء الطلب', 'en': 'Cancel Request'},

    // ===== Documents (Contracts) =====
    'no_documents': {'ar': 'لا توجد مستندات بعد', 'en': 'No documents yet'},
    'view_document': {'ar': 'عرض المستند', 'en': 'View'},
    'general': {'ar': 'عام', 'en': 'General'},

    // ===== Decisions (Voting) =====
    'no_decisions': {'ar': 'لا توجد قرارات مطروحة للتصويت', 'en': 'No decisions open for voting'},
    'vote_now': {'ar': 'صوّت الآن', 'en': 'Vote Now'},
    'you_voted': {'ar': 'لقد صوّتّ', 'en': 'You voted'},
    'votes_count': {'ar': 'صوت', 'en': 'votes'},
    'decision_open': {'ar': 'مفتوح للتصويت', 'en': 'Open for voting'},
    'decision_closed': {'ar': 'انتهى التصويت', 'en': 'Voting closed'},
    'vote_submitted': {'ar': 'تم تسجيل صوتك', 'en': 'Your vote has been recorded'},
    'new_decision': {'ar': 'قرار جديد للتصويت', 'en': 'New Decision'},
    'decision_title': {'ar': 'عنوان القرار', 'en': 'Decision Title'},
    'voting_options': {'ar': 'خيارات التصويت', 'en': 'Voting Options'},
    'option_label': {'ar': 'خيار', 'en': 'Option'},
    'add_option': {'ar': 'إضافة خيار', 'en': 'Add option'},
    'decision_created': {'ar': 'تم إنشاء القرار للتصويت', 'en': 'Decision created for voting'},
    'no_hotels_linked': {'ar': 'ما في فنادق مرتبطة بحسابك حالياً', 'en': 'No hotels linked to your account yet'},
    'no_units_available': {'ar': 'ما في وحدات مسجّلة بحسابك بعد لعرضها', 'en': 'You have no units yet to list'},
    'nightly_rental_hint': {'ar': 'اختر إحدى وحداتك وحدد سعر الليلة، بيقدر باقي الملاك يشوفوها ويحجزوها', 'en': "Pick one of your units and set a nightly rate for other owners to book"},
    'select_unit': {'ar': 'اختر الوحدة', 'en': 'Select Unit'},
    'price_per_night': {'ar': 'السعر بالليلة', 'en': 'Price per night'},
    'no_hotel_linked': {
      'ar': 'لا يوجد فندق مربوط بحسابك بعد. تواصل مع الإدارة لربط فندقك بحسابك.',
      'en': 'No hotel is linked to your account yet. Contact the admin to link your hotel.'
    },
    'add_unit': {'ar': 'إضافة وحدة', 'en': 'Add Unit'},
    'unit_name_ar': {'ar': 'اسم الوحدة (عربي)', 'en': 'Unit Name (Arabic)'},
    'unit_name_en': {'ar': 'اسم الوحدة (إنجليزي)', 'en': 'Unit Name (English)'},
    'unit_number': {'ar': 'رقم الوحدة', 'en': 'Unit Number'},
    'description_ar': {'ar': 'الوصف (عربي)', 'en': 'Description (Arabic)'},
    'description_en': {'ar': 'الوصف (إنجليزي)', 'en': 'Description (English)'},
    'capacity': {'ar': 'السعة', 'en': 'Capacity'},
    'price_per_week_optional': {'ar': 'السعر بالأسبوع (اختياري)', 'en': 'Price / week (optional)'},
    'price_per_month_optional': {'ar': 'السعر بالشهر (اختياري)', 'en': 'Price / month (optional)'},
    'cover_image': {'ar': 'الصورة الرئيسية', 'en': 'Cover image'},
    'hotel': {'ar': 'الفندق', 'en': 'Hotel'},
    'required_field': {'ar': 'هاد الحقل مطلوب', 'en': 'This field is required'},
    'add_unit_more_options_web': {
      'ar': 'تقدر تضيف صور إضافية، فترات إتاحة، وخيارات (سرير إضافي/وجبات) لهالوحدة لاحقاً من موقع الويب.',
      'en': 'You can add more photos, availability periods, and add-ons (extra bed/meals) for this unit later from the website.'
    },
    'unit_added_success': {'ar': 'تمت إضافة الوحدة بنجاح', 'en': 'Unit added successfully'},
    'unit_addons_title': {'ar': 'الإضافات (سرير إضافي / خطط وجبات)', 'en': 'Add-ons (extra bed / meal plans)'},
    'add_unit_addon': {'ar': 'إضافة خيار', 'en': 'Add option'},
    'addon_type': {'ar': 'النوع', 'en': 'Type'},
    'billed': {'ar': 'يُحسب', 'en': 'Billed'},
    'no_addons_yet': {'ar': 'ما في إضافات لهالوحدة بعد', 'en': 'No add-ons for this unit yet'},
    'gallery_images': {'ar': 'معرض الصور', 'en': 'Photo Gallery'},
    'add_photos': {'ar': 'إضافة صور', 'en': 'Add photos'},
    'add_unit_availability_web': {
      'ar': 'تقدر تحدد فترات الإتاحة لهالوحدة لاحقاً من موقع الويب.',
      'en': 'You can set availability periods for this unit later from the website.'
    },
    'add_unit_gallery_availability_web': {
      'ar': 'تقدر تضيف صور إضافية وفترات إتاحة لهالوحدة لاحقاً من موقع الويب.',
      'en': 'You can add more photos and availability periods for this unit later from the website.'
    },
    'extra_note': {'ar': 'ملاحظة إضافية (اختياري)', 'en': 'Extra note (optional)'},
    'price_prefilled_hint': {'ar': 'مُعبّى تلقائياً من سعر الوحدة، تقدر تعدله', 'en': 'Auto-filled from the unit price, you can edit it'},
    'fill_required_fields': {'ar': 'الرجاء تعبئة العنوان وخيارين على الأقل', 'en': 'Please fill the title and at least 2 options'},

    // ===== Community =====
    'no_posts': {'ar': 'لا توجد منشورات بعد، كن أول من ينشر', 'en': 'No posts yet — be the first to share'},
    'write_post': {'ar': 'اكتب منشوراً...', 'en': 'Write a post...'},
    'post': {'ar': 'نشر', 'en': 'Post'},
    'comments': {'ar': 'تعليقات', 'en': 'Comments'},
    'write_comment': {'ar': 'اكتب تعليقاً...', 'en': 'Write a comment...'},
    'like': {'ar': 'إعجاب', 'en': 'Like'},

    // ===== Marketplace =====
    'no_listings': {'ar': 'لا توجد وحدات معروضة حالياً', 'en': 'No listings yet'},
    'add_listing': {'ar': 'أضف عرضاً', 'en': 'Add Listing'},
    'listing_title': {'ar': 'عنوان العرض', 'en': 'Listing Title'},
    'listing_type': {'ar': 'نوع العرض', 'en': 'Listing Type'},
    'for_sale': {'ar': 'للبيع', 'en': 'For Sale'},
    'for_rent': {'ar': 'للإيجار', 'en': 'For Rent'},
    'price': {'ar': 'السعر', 'en': 'Price'},
    'im_interested': {'ar': 'أنا مهتم', 'en': "I'm Interested"},
    'interest_sent': {'ar': 'تم إرسال اهتمامك للمالك', 'en': 'Your interest was sent to the owner'},
    'property_apartment': {'ar': 'شقة', 'en': 'Apartment'},
    'property_studio': {'ar': 'استوديو', 'en': 'Studio'},
    'property_villa': {'ar': 'فيلا', 'en': 'Villa'},
    'property_room': {'ar': 'غرفة', 'en': 'Room'},
    'property_chalet': {'ar': 'شاليه', 'en': 'Chalet'},
    'property_commercial': {'ar': 'تجاري', 'en': 'Commercial'},
    'property_land': {'ar': 'أرض', 'en': 'Land'},
    'property_other': {'ar': 'أخرى', 'en': 'Other'},
    'area_sqm': {'ar': 'المساحة (م²)', 'en': 'Area (sqm)'},
    'bedrooms': {'ar': 'غرف النوم', 'en': 'Bedrooms'},
    'bathrooms': {'ar': 'الحمامات', 'en': 'Bathrooms'},
    'floor_number': {'ar': 'الطابق', 'en': 'Floor'},
    'furnished': {'ar': 'مفروش', 'en': 'Furnished'},
    'negotiable': {'ar': 'السعر قابل للتفاوض', 'en': 'Price negotiable'},
    'location_area': {'ar': 'الموقع / الحي', 'en': 'Location / Area'},
    'contact_number': {'ar': 'رقم التواصل (اختياري)', 'en': 'Contact number (optional)'},
    'sqm_short': {'ar': 'م²', 'en': 'sqm'},
    'more_details': {'ar': 'تفاصيل إضافية', 'en': 'More details'},
    'basic_info': {'ar': 'معلومات أساسية', 'en': 'Basic info'},

    // ===== Messages =====
    'no_conversations': {'ar': 'لا توجد محادثات بعد', 'en': 'No conversations yet'},
    'type_message': {'ar': 'اكتب رسالة...', 'en': 'Type a message...'},
    'new_message': {'ar': 'رسالة جديدة', 'en': 'New Message'},
    'select_recipient': {'ar': 'اختر المستلم', 'en': 'Select Recipient'},
  };

  static String t(bool isArabic, String key) {
    final entry = _strings[key];
    if (entry == null) return key;
    return entry[isArabic ? 'ar' : 'en'] ?? key;
  }
}